---
- name: ensure pip is installed
  apt:
    name:
      - python3-pip
      - python3-setuptools
    state: present

- name: install python docker packages
  pip:
    name:
      - docker
      - docker-compose
    state: present

- name: create greenlight directory
  file:
    path: /root/greenlight
    state: directory

- name: register bbb secret
  command: bbb-conf --secret
  register: result
  when: not bbb_secret is defined

- name: parse bbb secret
  set_fact:
    bbb_secret: "{{ result.stdout | regex_search('Secret: ([a-zA-Z0-9]*)', multiline=True) |  regex_replace('Secret: ') }}"
    cacheable: true
  when: not bbb_secret is defined

- name: copy greenlight config file
  template:
    src: greenlight/env.j2
    dest: /root/greenlight/.env

- name: copy greenlight docker compose file
  template:
    src: greenlight/docker-compose.yml.j2
    dest: /root/greenlight/docker-compose.yml

- name: copy greenlight nginx configuration file
  template:
    src: greenlight/greenlight.nginx.j2
    dest: /etc/bigbluebutton/nginx/greenlight.nginx
  notify: reload nginx

- block:
    - name: start greenlight
      docker_compose:
        pull: true
        project_src: /root/greenlight/

    # https://docs.bigbluebutton.org/greenlight/gl-admin.html#creating-accounts
    - name: Create greenlight users
      command: >
        docker exec greenlight-v2 bundle exec rake user:create["{{ item.name }}","{{ item.email }}","{{ item.password }}","{{ item.type }}"]
      with_items: "{{ bbb_greenlight_users }}"

  when: bbb_greenlight_enable
