---

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart coturn
  service:
    name: coturn
    state: reloaded

- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: restart bigbluebutton
  command: bbb-conf --restart
  become: true

- name: restart mongo
  service:
    name: mongod
    state: restarted
